services:
    git_repository_provider:
        class: Packagist\WebBundle\Repository\Provider\GitHubProvider

    repository_provider:
        class: Packagist\WebBundle\Repository\RepositoryProvider
        calls:
            - [ addProvider, [ @git_repository_provider ] ]
