services:
    git_repository_provider:
        class: Packagist\WebBundle\Repository\Provider\GitRepositoryProvider
        
    repository_provider:
        class: Packagist\WebBundle\Repository\RepositoryProviderProvider
        calls:
            - [ addProvider, [ @git_repository_provider ] ]
